"""add mcp_servers

Revision ID: 418dc608c079
Revises: df1e21c2b785
Create Date: 2026-07-30 17:04:03.898329
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '418dc608c079'
down_revision: Union[str, None] = 'df1e21c2b785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('transport', sa.String(length=8), nullable=False),
    sa.Column('command', sa.String(length=255), nullable=True),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('env', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: alembic autogenerate wanted to drop+recreate ix_document_chunks_embedding and
    # ix_memory_facts_embedding here - false positive, same as in earlier migrations
    # (raw op.execute() HNSW indexes, invisible to autogenerate's metadata diff). Removed
    # those lines; the indexes are untouched by this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
