"""add google_accounts

Revision ID: 9bc0029049c8
Revises: 418dc608c079
Create Date: 2026-07-30 18:37:15.048615
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9bc0029049c8'
down_revision: Union[str, None] = '418dc608c079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('google_email', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # NOTE: alembic autogenerate wanted to drop+recreate ix_document_chunks_embedding and
    # ix_memory_facts_embedding here - false positive, same as in earlier migrations
    # (raw op.execute() HNSW indexes, invisible to autogenerate's metadata diff). Removed
    # those lines; the indexes are untouched by this migration.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('google_accounts')
    # ### end Alembic commands ###
